Phpfol 2 feat: create dockerfiles and update readme
JasonBenett/phpfolio pull request #12
Opened 2021-04-05 16:56 UTC by sophiearnou

Phpfol 2 feat: create dockerfiles and update readme

2021-04-05 17:00 UTC, Dev-Int requested changes

2021-04-05 17:00 UTC, Dev-Int commented on README.md
> +docker exec -it phpfolio_php-fpm-8_1 sh
`phpfolio_php-fpm-8_1` is the name of container on **your** machine. 
Prefer use `docker-compose` to use the service name, like `php-fpm-8`.

2021-04-05 17:00 UTC, Dev-Int commented on README.md
> +docker exec -it phpfolio_php-fpm-7.4_1 sh
Same to `php-fpm-8`

2021-04-05 19:36 UTC, Coralie-BDY commented
OK  I see it

2021-04-11 16:47 UTC, Dev-Int approved these changes

2021-04-11 16:52 UTC, JasonBenett approved these changes

2021-04-11 16:55 UTC, merged