PHPFOL-6 feat : add composer.json and .gitignore
JasonBenett/phpfolio pull request #9
Opened 2021-03-31 18:25 UTC by toutvukantabu

2021-03-31 19:53 UTC, JasonBenett requested changes

2021-03-31 19:53 UTC, JasonBenett commented on composer.json
> +    "description": "Composer helps you declare, manage and install dependencies of PHP projects. It ensures you have the right stack everywhere.",
We need to find a description of the project.

2021-03-31 19:53 UTC, JasonBenett commented on composer.json
> +    "keywords": ["phpfolio", "What The Fabrik Community", "Jason Benetti"],
You can remove my full name from the keywords.

2021-03-31 19:53 UTC, JasonBenett commented on composer.json
> +            "name": "Jason Benetti",
This is not my name 😂

2021-03-31 19:53 UTC, JasonBenett commented on composer.json
> +            "email": ""
jason.benedetti@live.fr

2021-03-31 19:53 UTC, JasonBenett commented on composer.json
> +
Pls remove useless blank lines

2021-03-31 19:53 UTC, JasonBenett commented on composer.json
> +        "php": "^7.4 || ^8.0"
No need to repeat in the require dev section what is already in the require section

2021-03-31 19:53 UTC, JasonBenett commented on composer.json
> +    "config": {
Let's move this to the bottom of the file. It's less important to see it first

2021-03-31 19:53 UTC, JasonBenett commented on composer.json
> +
Nice, let's consider that our codebase will be in a "src" folder. And our project root namespace will be "JasonBenett/Phpfolio". Please update accordingly.

2021-03-31 19:56 UTC, toutvukantabu commented on composer.json
> +    "config": {
ok

2021-03-31 19:58 UTC, toutvukantabu commented on composer.json
> +            "email": ""
ok

2021-03-31 19:58 UTC, toutvukantabu commented on composer.json
> +
ok

2021-03-31 19:58 UTC, toutvukantabu commented on composer.json
> +        "php": "^7.4 || ^8.0"
ok, i 've removed "require-dev"

2021-03-31 20:00 UTC, toutvukantabu commented on composer.json
> +    "keywords": ["phpfolio", "What The Fabrik Community", "Jason Benetti"],
ok

2021-03-31 20:44 UTC, JasonBenett commented on composer.json
> +        "php": " ^7.4 || ^8.0"
"^7.4|^8.0"

2021-03-31 20:45 UTC, JasonBenett commented on .gitignore
> +/vendor/
Add composer.lock too + run composer install just to be sure that it works

2021-04-01 07:10 UTC, toutvukantabu commented on .gitignore
> +/vendor/
ok

2021-04-02 08:03 UTC, toutvukantabu commented on composer.json
> +        "php": " ^7.4 || ^8.0"
ok

2021-04-02 08:05 UTC, toutvukantabu commented
It's good for me, I'm awaiting your return

2021-04-02 08:39 UTC, JasonBenett approved these changes

2021-04-02 18:49 UTC, Dev-Int approved these changes

2021-04-02 19:21 UTC, merged